(Firefox fix) - Remove User Agent header from headers list
Aathish04/moodlearchiver pull request #5
Opened 2024-12-19 05:42 UTC by TotalyEnglizLitrate

Remove User Agent header that was causing a CORS Missing Allow Header error. See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowHeaderFromPreflight for more

2024-12-19 07:52 UTC, TotalyEnglizLitrate commented
Also added a check to see if a module has contents or not, and skip the module if `module["contents"]` is `undefined` i.e empty

2024-12-22 04:01 UTC, Aathish04 requested changes

2024-12-22 04:01 UTC, Aathish04 commented on README.md
> +    This website was only tested with the LMS of SSN College of Engineering/SNU Chennai, but you can enter your own institution's Moodle Backend, and it should still work.
The line should read "... the LMSes of SSN College of Engineering and Shiv Nadar University Chennai". People already get confused between the institutions and I'm not going to contribute to that problem 😆

2024-12-24 17:12 UTC, Aathish04 approved these changes

2024-12-24 17:12 UTC, merged